project_id = "yquuidpajigvecyonqir"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54320
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_signup = true
enable_anonymous_sign_ins = false

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[functions.send-contact-email]
verify_jwt = false

[functions.send-chat-notification]
verify_jwt = false

[functions.chat-ai]
verify_jwt = false

[functions.seed-blog-posts]
verify_jwt = false

[functions.update-blog-dates]
verify_jwt = false