// Auto-generated from src/data/locations.ts — DO NOT EDIT MANUALLY
// Maps: countryCode -> stateSlug -> Set of citySlugs
export const validLocations = {
  "ae": {
    "abu-dhabi": new Set([]),
    "ajman": new Set([]),
    "dubai": new Set([]),
    "ras-al-khaimah": new Set([]),
    "sharjah": new Set([]),
  },
  "au": {
    "act": new Set([]),
    "new-south-wales": new Set([]),
    "northern-territory": new Set([]),
    "queensland": new Set([]),
    "south-australia": new Set([]),
    "tasmania": new Set([]),
    "victoria": new Set([]),
    "western-australia": new Set([]),
  },
  "ca": {
    "alberta": new Set([]),
    "british-columbia": new Set([]),
    "manitoba": new Set([]),
    "ontario": new Set([]),
    "quebec": new Set([]),
    "saskatchewan": new Set([]),
  },
  "in": {
    "assam": new Set([]),
    "bihar": new Set([]),
    "chandigarh": new Set([]),
    "chhattisgarh": new Set([]),
    "delhi-ncr": new Set([]),
    "goa": new Set([]),
    "gujarat": new Set([]),
    "haryana": new Set([]),
    "himachal-pradesh": new Set([]),
    "jharkhand": new Set([]),
    "karnataka": new Set([]),
    "kerala": new Set([]),
    "madhya-pradesh": new Set([]),
    "maharashtra": new Set([]),
    "odisha": new Set([]),
    "punjab": new Set([]),
    "rajasthan": new Set([]),
    "tamil-nadu": new Set([]),
    "telangana": new Set([]),
    "uttar-pradesh": new Set([]),
    "uttarakhand": new Set([]),
    "west-bengal": new Set([]),
  },
  "kw": {
    "kuwait-city": new Set([]),
  },
  "uk": {
    "england": new Set([]),
    "northern-ireland": new Set([]),
    "scotland": new Set([]),
    "wales": new Set([]),
  },
  "usa": {
    "alabama": new Set([]),
    "alaska": new Set([]),
    "arizona": new Set([]),
    "arkansas": new Set([]),
    "california": new Set([]),
    "colorado": new Set([]),
    "connecticut": new Set([]),
    "delaware": new Set([]),
    "florida": new Set([]),
    "georgia": new Set([]),
    "hawaii": new Set([]),
    "idaho": new Set([]),
    "illinois": new Set([]),
    "indiana": new Set([]),
    "iowa": new Set([]),
    "kansas": new Set([]),
    "kentucky": new Set([]),
    "louisiana": new Set([]),
    "maine": new Set([]),
    "maryland": new Set([]),
    "massachusetts": new Set([]),
    "michigan": new Set([]),
    "minnesota": new Set([]),
    "mississippi": new Set([]),
    "missouri": new Set([]),
    "montana": new Set([]),
    "nebraska": new Set([]),
    "nevada": new Set([]),
    "new-hampshire": new Set([]),
    "new-jersey": new Set([]),
    "new-mexico": new Set([]),
    "new-york": new Set([]),
    "north-carolina": new Set([]),
    "north-dakota": new Set([]),
    "ohio": new Set([]),
    "oklahoma": new Set([]),
    "oregon": new Set([]),
    "pennsylvania": new Set([]),
    "rhode-island": new Set([]),
    "south-carolina": new Set([]),
    "south-dakota": new Set([]),
    "tennessee": new Set([]),
    "texas": new Set([]),
    "utah": new Set([]),
    "vermont": new Set([]),
    "virginia": new Set([]),
    "washington": new Set([]),
    "west-virginia": new Set([]),
    "wisconsin": new Set([]),
    "wyoming": new Set([]),
  },
};

export const validCountryCodes = new Set(Object.keys(validLocations));

export function isValidLocation(country, state, city) {
  const countryData = validLocations[country];
  if (!countryData) return false;
  if (!state) return true;
  const stateData = countryData[state];
  if (!stateData) return false;
  if (!city) return true;
  return stateData.has(city);
}